spring:
  application:
    name: stats-generator
stats-generator:
  github-repository-base-url: https://github.com/savra/LeetCode/blob/master/src/main/java/com/hvdbs/leetcode/solution
  language:
    - Java
    - SQL
  sql-dialect:
    - Oracle
    - Postgres
  solution-package-name: com.hvdbs.leetcode.solution